version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run: echo "hoge"
      - run: pip install -r requirements.txt
        # name: Install Dependencies
        # command: echo "hoge"
        # command: pip install -r reqquirements.txt
