version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: python:3.4.2
      - image: mysql:5.6
    steps:
      - checkout
      - run: echo "foo"
      - run: pip install -r requirements.txt
      - run: py.test
      - run:
          name: TEST
          command: |
            echo "sharding_map"
