version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.4.2
    steps:
      - checkout
      - run:
        # name: Install Dependencies
        command: pip install -r reqquirements.txt
      - run:
        name: Python Test
        command: py.test
